### ISSUE TITLE
Customize fill color for features. 

### ISSUE THREAD

**Issue by yuans-cellbio** [moritzlindner/ggped#1]
Nice work Moritz! 

Is there an option to customize the fill color of `GeomPedigreePoint` by the feature? I tried `scale_fill_*`, but they don't seem to control the fill color.  

I noticed `feature.name` is coerced to color hex codes when passed to `draw_panel` or `draw_key`, which is used as the fill color. Where does this conversion happen? 

I was able to alter the code to pass a custom color palette `feature.colours` and replace the fill logic in  `GeomPedigreePoint`, which effectively changes the fill color. However, `feature.colours` is not successfully passed to `draw_key`, so the legend does not show the right fill color. 

I don't understand how the fill color is handled differently by `draw_panel` and `draw_key`. I hope you have a better solution. Thanks!

**Comment by yuans-cellbio** [comment]
I figured it out. This function is implemented in `scale_feature.name()`. It would also be helpful to add a `scale_feature.name_manual`. 

```
scale_feature.name_manual<-function(...,
                                      values = NULL,
                                      na.value = "grey50",
                                      main.feature.black=TRUE,
                                      name="Features") {
  discrete_scale(
    aesthetics = "feature.name", 
    scale_name = "feature.name_d", 
    palette = function(x){
      palette<-values
      if(main.feature.black){
        palette<-c("#000000",palette[-1])
      }else{
        palette
      }
    },
    name=name,
    drop=F,
    na.value = na.value,
    ...
  )
}
```

Another suggestion is to change `feature.value` from logical to numeric, and change the fill color's intensity from 0-1. This allows the symbol to show a degree of changes in the feature. 

```
 setup_data = function(data, param) {
    # Check if 'sex' is a factor
    if (!is.factor(data$sex)) {
      stop("The 'sex' column must be of class 'factor'.")
    }
    
    # Check if 'isdead' is either a factor or a logical vector
    if (!is.factor(data$isdead) && !is.logical(data$isdead)) {
      stop("The 'isdead' column must be of class 'factor' or 'logical'.")
    }

    # 'feature.value' is modified to take a value 0-1. 
    
    if (!is.numeric(data$feature.value)) {
      stop("The 'feature.value' column must be a number.")
      } else if (any(data$feature.value < 0 | data$feature.value > 1)) {
      stop("The 'feature.value' column must be between 0 and 1.")
    }
    
    data
  }
``` 

```
draw_panel = function(data,
                        panel_scales,
                        coord,
                        na.colour,
                        size) {
...
      # Feature status (Fill)
      
      # The Fill logic is modified to fill a color which intensity changes according to feature.value (0-1). 

      calculate_lighter_color_hex <- function(darker_color_hex, alpha) {
        # Convert the hex color to RGB
        darker_color <- col2rgb(darker_color_hex)
        
        # Assuming the background is white
        background_color <- c(255, 255, 255)
        
        # Calculate the lighter color in the normalized 0-1 range
        lighter_color <- alpha * darker_color + (1 - alpha) * background_color
        
        # Convert the RGB to hex
        lighter_color_hex <- rgb(lighter_color[1,], lighter_color[2,], lighter_color[3,], maxColorValue=255)
        
        return(tolower(lighter_color_hex))
      }
      
      if (is.na(data$feature.value[i])) {
        fill <- c(fill, na.colour)
      } else {
        fill <- c(fill, calculate_lighter_color_hex(data$feature.name[i], data$feature.value[i]))
      }
...
    }
}
```

**Comment by moritzlindner** [comment]
Thanks a lot for your suggestions! Seems very reasonable to me.

 

My desk is a bit piled up at the moment. So ill unfortunately need until early December to implement the functions.

 

Tanks again and best,

Moritz

 

Von: yuans-cellbio ***@***.***> 
Gesendet: 06 November 2023 04:47
An: moritzlindner/ggped ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: Re: [moritzlindner/ggped] Customize fill color for features. (Issue #1)

 

I figured it out. This function is implemented in scale_feature.name(). It would also be helpful to add a scale_feature.name_manual.

scale_feature.name_manual<-function(...,
                                      values = NULL,
                                      na.value = "grey50",
                                      main.feature.black=TRUE,
                                      name="Features") {
  discrete_scale(
    aesthetics = "feature.name", 
    scale_name = "feature.name_d", 
    palette = function(x){
      palette<-values
      if(main.feature.black){
        palette<-c("#000000",palette[-1])
      }else{
        palette
      }
    },
    name=name,
    drop=F,
    na.value = na.value,
    ...
  )
}

Another suggestion is to change feature.value from logical to numeric, and change the fill color's intensity from 0-1. This allows the symbol to show a degree of changes in the feature.

 setup_data = function(data, param) {
    # Check if 'sex' is a factor
    if (!is.factor(data$sex)) {
      stop("The 'sex' column must be of class 'factor'.")
    }
    
    # Check if 'isdead' is either a factor or a logical vector
    if (!is.factor(data$isdead) && !is.logical(data$isdead)) {
      stop("The 'isdead' column must be of class 'factor' or 'logical'.")
    }
 
    # 'feature.value' is modified to take a value 0-1. 
    
    if (!is.numeric(data$feature.value)) {
      stop("The 'feature.value' column must be a number.")
      } else if (any(data$feature.value < 0 | data$feature.value > 1)) {
      stop("The 'feature.value' column must be between 0 and 1.")
    }
    
    data
  }
draw_panel = function(data,
                        panel_scales,
                        coord,
                        na.colour,
                        size) {
...
      # Feature status (Fill)
      
      # The Fill logic is modified to fill a color which intensity changes according to feature.value (0-1). 
 
      calculate_lighter_color_hex <- function(darker_color_hex, alpha) {
        # Convert the hex color to RGB
        darker_color <- col2rgb(darker_color_hex)
        
        # Assuming the background is white
        background_color <- c(255, 255, 255)
        
        # Calculate the lighter color in the normalized 0-1 range
        lighter_color <- alpha * darker_color + (1 - alpha) * background_color
        
        # Convert the RGB to hex
        lighter_color_hex <- rgb(lighter_color[1,], lighter_color[2,], lighter_color[3,], maxColorValue=255)
        
        return(tolower(lighter_color_hex))
      }
      
      if (is.na(data$feature.value[i])) {
        fill <- c(fill, na.colour)
      } else {
        fill <- c(fill, calculate_lighter_color_hex(data$feature.name[i], data$feature.value[i]))
      }
...
    }
}
