### ISSUE TITLE
Warnings when plotting pedigree

### ISSUE THREAD

**Issue by rivasiker** [moritzlindner/ggped#2]
Hi, @moritzlindner!

I have run the example that you show in the README.md and I get the following warnings:
```
Warning: Removed 1 row containing missing values or values outside the scale range (`geom_text()`).
Warning: Removed 7 rows containing missing values or values outside the scale range (`geom_segment()`).
Warning: Removed 7 rows containing missing values or values outside the scale range (`geom_segment()`).
Warning: Removed 26 rows containing missing values or values outside the scale range (`geom_line()`).
```
and the resulting plot looks a bit odd, specially around the leftmost corner (individuals 139 and 140, and 137 and 138):

![image](https://github.com/user-attachments/assets/56fa10d8-5307-475f-8d04-3065c70cf90a)

Meanwhile, the pedigree plotted using base R and `kinship2` looks like so:

![image](https://github.com/user-attachments/assets/a0cf5943-ff6d-4803-9f3b-4a25d409e814)

I have run the code with another pedigree of mine, and I get similar issues.

Thanks for the help!

**Comment by moritzlindner** [comment]
Hi @rivasiker,
Thanks for your message.
The strange appearence of the twins 137 and 138 appars to be caused by ggped incorreclty handling dicygocity. I will have a look into it, but it might take me a couple of weeks.
This horizontal line left of the root of twins 139 and 140 does not appear if I draw the tree running the example code. could you tell me which versions of kinship2 and ggplot2 you are using?
Thanks and best wishes

**Comment by rivasiker** [comment]
Hi @moritzlindner,

Thanks for the quick reply! After running `sessionInfo()`:

```
R version 4.4.1 (2024-06-14)
Platform: aarch64-apple-darwin20
Running under: macOS Sonoma 14.5

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: Europe/Berlin
tzcode source: internal

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets 
[7] methods   base     

other attached packages:
[1] ggped_0.9.8        RColorBrewer_1.1-3 tidyr_1.3.1       
[4] ggplot2_3.5.1      kinship2_1.9.6.1   quadprog_1.5-8    
[7] Matrix_1.7-0      

loaded via a namespace (and not attached):
 [1] vctrs_0.6.5       cli_3.6.3         knitr_1.48       
 [4] rlang_1.1.4       xfun_0.46         purrr_1.0.2      
 [7] generics_0.1.3    glue_1.7.0        colorspace_2.1-0 
[10] scales_1.3.0      fansi_1.0.6       munsell_0.5.1    
[13] tibble_3.2.1      lifecycle_1.0.4   compiler_4.4.1   
[16] dplyr_1.1.4       pkgconfig_2.0.3   rstudioapi_0.16.0
[19] lattice_0.22-6    R6_2.5.1          tidyselect_1.2.1 
[22] utf8_1.2.4        pillar_1.9.0      magrittr_2.0.3   
[25] tools_4.4.1       withr_3.0.0       gtable_0.3.5 
```

**Comment by moritzlindner** [comment]
Hi @rivasiker,
i have corrected the code and tested it with the latest versions of kinship2 and ggplot2. issues seem solved. let me know if its now working for you as well.

**Comment by rivasiker** [comment]
Hi @moritzlindner,

After installing the latest `ggped` version from GitHub, the pedigree looks like so:

![image](https://github.com/user-attachments/assets/67d1d97d-f71e-4027-be34-32db0e07dceb)

I think there might still be some problems with individuals 139 and 140. 

Additionally, I have tried plotting a pedigree of mine, which I attach here as a csv file:
[sample_ped.csv](https://github.com/user-attachments/files/16784050/sample_ped.csv). After running the following code
```
library(kinship2)
library(ggped)

sample_ped <- read.csv("~/Documents/Projects/SLiM_testing/real_data/sample_ped.csv")
ped_test <- pedigree(
  id = sample_ped$id, 
  dadid = sample_ped$dadid, 
  momid = sample_ped$momid, 
  sex = sample_ped$sex)
plot(ped_test)

dfalign.pedigree(ped_test) |> 
  ggdraw.pedigree() 
```
the two plots I get look like so:
- using `kinship2`:

![image](https://github.com/user-attachments/assets/c4f784da-b1f7-48a4-a772-3a4cbfa56d48)
- using `ggped`:

![image](https://github.com/user-attachments/assets/76ca071c-fa2f-4c98-bbce-c7a3a7a1d6e9)

As you can see, there are quite some differences between the two. It looks like some of the connections are not well done in `ggped`.

My `sessionInfo()` is the following:
```
R version 4.4.1 (2024-06-14)
Platform: aarch64-apple-darwin20
Running under: macOS Sonoma 14.5

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: Europe/Berlin
tzcode source: internal

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggped_0.9.9        cli_3.6.3          RColorBrewer_1.1-3 tidyr_1.3.1        ggplot2_3.5.1      kinship2_1.9.6.1   quadprog_1.5-8    
[8] Matrix_1.7-0      

loaded via a namespace (and not attached):
 [1] vctrs_0.6.5       knitr_1.48        rlang_1.1.4       xfun_0.47         purrr_1.0.2       generics_0.1.3    labeling_0.4.3   
 [8] glue_1.7.0        colorspace_2.1-1  scales_1.3.0      fansi_1.0.6       munsell_0.5.1     tibble_3.2.1      lifecycle_1.0.4  
[15] compiler_4.4.1    dplyr_1.1.4       pkgconfig_2.0.3   rstudioapi_0.16.0 farver_2.1.2      lattice_0.22-6    R6_2.5.1         
[22] tidyselect_1.2.1  utf8_1.2.4        pillar_1.9.0      magrittr_2.0.3    tools_4.4.1       withr_3.0.1       gtable_0.3.5     
```

I hope this can help debug!

**Comment by moritzlindner** [comment]
hi @rivasiker,
I had been looking into this for the last few days.

The complexity with your pedigree stems from the need to represent some subjects more than once (e.g., across different generations). This affects how the positions of offspring are calculated. The ggped package relies on low-level functions from kinship2 to compute these positions, but it seems the plot.pedigree function from kinship2 includes some additional calculations that I haven’t fully been able to isolate yet.

Unfortunately, addressing this issue requires a substantial time investment, which exceeds the current capacity of our lab. For now, I’ve implemented an error message (which can be bypassed with allow.repeated=T), but a full resolution would need more dedicated work.

Regarding the issue with subjects 139 and 140 (where the bar extends too far left), I wasn’t able to reproduce this on my end, despite testing with identical versions of ggplot and kinship2.
